# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Silex Data Solutions - VAR and Systems Integrator
email: info@silexdata.com
description: > # this means to ignore newlines until "baseurl:"
  We are a VAR and Systems Integrator. Woot!
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://silexdata.com" # the base hostname & protocol for your site
twitter_username: SilexData


# Build settings
markdown: kramdown
